"""Configuration for recruitment and promo summary embeds."""

from __future__ import annotations

SUMMARY_LAYOUTS = {
    "welcome": {
        "frame": {
            "title": "C1C • Recruitment Summary",
            "description": "Keep this thread open until a recruiter confirms placement.",
            "icon": "crest_or_blue_flame",
            "color": "c1c_blue",
            "footer": "C1C Recruitment • Summary generated by The Woadkeeper",
        },
        "sections": [
            {
                "name": "identity",
                "fields": [
                    {"gid": "w_ign", "label": "Ingame Name"},
                    {
                        "gid": "w_power",
                        "label": "Power",
                        "inline_with": "w_level_detail",
                        "fmt": "abbr_number",
                    },
                    {"gid": "w_level_detail", "label": "Bracket", "inline": True},
                    {"gid": "w_playstyle", "label": "Playstyle"},
                    {"gid": "w_clan", "label": "Looking for"},
                ],
            },
            {
                "name": "bossing",
                "fields": [
                    {"gid": "w_CB", "label": "Clan Boss (one-key top chest)"},
                    {"gid": "w_hydra_diff", "label": "Hydra"},
                    {
                        "gid": "w_hydra_clash",
                        "label": "Avg Hydra Clash",
                        "inline_with": "w_hydra_diff",
                        "fmt": "abbr_number",
                    },
                    {"gid": "w_chimera_diff", "label": "Chimera"},
                    {
                        "gid": "w_chimera_clash",
                        "label": "Avg Chimera Clash",
                        "inline_with": "w_chimera_diff",
                        "fmt": "abbr_number",
                    },
                ],
            },
            {
                "name": "war",
                "fields": [
                    {"gid": "w_siege", "label": "Siege participation", "force_show": True},
                    {
                        "gid": "w_siege_detail",
                        "label": "Siege setup",
                        "hide_if_values": ["", "no", "none"],
                        "requires": "w_siege",
                    },
                    {
                        "gid": "w_cvc",
                        "label": "CvC priority",
                        "fmt": "cvc_priority",
                        "inline_with": "w_cvc_points",
                    },
                    {
                        "gid": "w_cvc_points",
                        "label": "Minimum CvC points",
                        "fmt": "abbr_number",
                        "inline": True,
                    },
                ],
            },
            {
                "name": "notes",
                "fields": [
                    {
                        "gid": "w_level",
                        "label": "Progression (self-feel)",
                        "optional": True,
                        "truncate": 200,
                    },
                    {"gid": "w_origin", "label": "Heard about C1C from"},
                ],
            },
        ],
        "section_titles": {
            "bossing": "🧩 Progress & Bossing",
            "war": "⚔️ War Modes",
            "notes": "🧭 Notes",
        },
    },
    "promo.r": {
        "frame": {
            "title": "🔥 C1C • Returning player promo",
            "description": (
                "Got your request! A coordinator will review your return and follow up here.\n"
                "Please leave the thread unlocked until we reply."
            ),
            "icon": "",
            "color": "c1c_blue",
            "footer": "C1C Recruitment • Summary generated by The Woadkeeper",
        },
        "sections": [
            {
                "name": "identity",
                "title": "🧭 Identity & return intent",
                "fields": [
                    {"gid": "pr_ign", "label": "Player"},
                    {
                        "gid": "pr_power",
                        "label": "Power",
                        "inline_with": "pr_level_detail",
                        "fmt": "abbr_number",
                    },
                    {"gid": "pr_level_detail", "label": "Bracket", "inline": True},
                    {"gid": "pr_playstyle", "label": "Playstyle"},
                    {"gid": "pr_prev_clan", "label": "Last clan played in"},
                    {"gid": "pr_clan", "label": "Looking for"},
                ],
            },
            {
                "name": "progress",
                "title": "🧩 Past progress & bossing",
                "fields": [
                    {"gid": "pr_CB", "label": "Clan Boss (one-key top chest)"},
                    {"gid": "pr_hydra_diff", "label": "Hydra"},
                    {
                        "gid": "pr_hydra_clash",
                        "label": "Avg Hydra Clash",
                        "inline_with": "pr_hydra_diff",
                        "fmt": "abbr_number",
                    },
                    {"gid": "pr_chimera_diff", "label": "Chimera"},
                    {
                        "gid": "pr_chimera_clash",
                        "label": "Avg Chimera Clash",
                        "inline_with": "pr_chimera_diff",
                        "fmt": "abbr_number",
                    },
                ],
            },
            {
                "name": "war",
                "title": "⚔️ War Modes",
                "fields": [
                    {"gid": "pr_siege", "label": "Siege participation", "force_show": True},
                    {
                        "gid": "pr_siege_detail",
                        "label": "Siege setup",
                        "hide_if_values": ["", "no", "none"],
                        "requires": "pr_siege",
                    },
                    {
                        "gid": "pr_cvc",
                        "label": "CvC priority",
                        "fmt": "cvc_priority",
                        "inline_with": "pr_cvc_points",
                    },
                    {
                        "gid": "pr_cvc_points",
                        "label": "Minimum CvC points",
                        "fmt": "abbr_number",
                        "inline": True,
                    },
                ],
            },
            {
                "name": "context",
                "title": "🧭 Return context & notes",
                "fields": [
                    {"gid": "pr_return_reason", "label": "Reason for break", "truncate": 200},
                    {"gid": "pr_return_change", "label": "What changed / why now", "truncate": 200},
                    {"gid": "pr_notes", "label": "Anything else we should know", "truncate": 280},
                ],
            },
        ],
    },
    "promo.m": {
        "frame": {
            "title": "🔥 C1C • Move request received",
            "description": (
                "Got your request! A coordinator will review your move and follow up here.\n"
                "Please leave the thread unlocked until we reply."
            ),
            "icon": "",
            "color": "c1c_blue",
            "footer": "C1C Recruitment • Summary generated by The Woadkeeper",
        },
        "sections": [
            {
                "name": "identity",
                "title": "🧭 Player & current placement",
                "fields": [
                    {"gid": "pm_ign", "label": "Player"},
                    {
                        "gid": "pm_power",
                        "label": "Power",
                        "inline_with": "pm_level_detail",
                        "fmt": "abbr_number",
                    },
                    {"gid": "pm_level_detail", "label": "Bracket", "inline": True},
                    {"gid": "pm_playstyle", "label": "Playstyle"},
                    {"gid": "pm_current_clan", "label": "Current clan"},
                    {"gid": "pm_clan_type", "label": "Looking for"},
                ],
            },
            {
                "name": "performance",
                "title": "🧩 Performance snapshot",
                "fields": [
                    {"gid": "pm_CB", "label": "Clan Boss (one-key top chest)"},
                    {"gid": "pm_hydra_diff", "label": "Hydra"},
                    {
                        "gid": "pm_hydra_clash",
                        "label": "Avg Hydra Clash",
                        "inline_with": "pm_hydra_diff",
                        "fmt": "abbr_number",
                    },
                    {"gid": "pm_chimera_diff", "label": "Chimera"},
                    {
                        "gid": "pm_chimera_clash",
                        "label": "Avg Chimera Clash",
                        "inline_with": "pm_chimera_diff",
                        "fmt": "abbr_number",
                    },
                ],
            },
            {
                "name": "war",
                "title": "⚔️ War Modes",
                "fields": [
                    {"gid": "pm_siege", "label": "Siege participation", "force_show": True},
                    {
                        "gid": "pm_siege_detail",
                        "label": "Siege setup",
                        "hide_if_values": ["", "no", "none"],
                        "requires": "pm_siege",
                    },
                    {
                        "gid": "pm_cvc",
                        "label": "CvC priority",
                        "fmt": "cvc_priority",
                        "inline_with": "pm_cvc_points",
                    },
                    {
                        "gid": "pm_cvc_points",
                        "label": "Minimum CvC points",
                        "fmt": "abbr_number",
                        "inline": True,
                    },
                ],
            },
            {
                "name": "intent",
                "title": "🧭 Move intent & notes",
                "fields": [
                    {"gid": "pm_move_urgency", "label": "Move urgency"},
                    {"gid": "pm_move_date", "label": "Move date"},
                    {"gid": "pm_move_reason", "label": "Move reason", "truncate": 200},
                    {"gid": "pm_notes", "label": "Anything else we should know", "truncate": 280},
                ],
            },
        ],
    },
    "promo.l": {
        "frame": {
            "title": "🔥 C1C • Leadership move request",
            "description": (
                "Got your request! A coordinator will review the move and follow up here.\n"
                "Please leave the thread unlocked until we reply."
            ),
            "icon": "",
            "color": "c1c_blue",
            "footer": "C1C Recruitment • Summary generated by The Woadkeeper",
        },
        "sections": [
            {
                "name": "identity",
                "title": "🧭 Player & reporter",
                "fields": [
                    {"gid": "pl_player_name", "label": "Player"},
                    {"gid": "pl_reporter", "label": "Reported by"},
                    {"gid": "pl_current_clan", "label": "Current clan"},
                    {"gid": "pl_target_clan", "label": "Target clan"},
                ],
            },
            {
                "name": "performance",
                "title": "🧩 Performance snapshot",
                "fields": [
                    {
                        "gid": "pl_power",
                        "label": "Power",
                        "inline_with": "pl_level_detail",
                        "fmt": "abbr_number",
                    },
                    {"gid": "pl_level_detail", "label": "Bracket", "inline": True},
                    {"gid": "pl_playstyle", "label": "Playstyle"},
                    {"gid": "pl_CB", "label": "Clan Boss (one-key top chest)"},
                    {"gid": "pl_hydra_diff", "label": "Hydra"},
                    {
                        "gid": "pl_hydra_clash",
                        "label": "Avg Hydra Clash",
                        "inline_with": "pl_hydra_diff",
                        "fmt": "abbr_number",
                    },
                    {"gid": "pl_chimera_diff", "label": "Chimera"},
                    {
                        "gid": "pl_chimera_clash",
                        "label": "Avg Chimera Clash",
                        "inline_with": "pl_chimera_diff",
                        "fmt": "abbr_number",
                    },
                ],
            },
            {
                "name": "war",
                "title": "⚔️ War Modes",
                "fields": [
                    {"gid": "pl_siege", "label": "Siege participation", "force_show": True},
                    {
                        "gid": "pl_siege_detail",
                        "label": "Siege setup",
                        "hide_if_values": ["", "no", "none"],
                        "requires": "pl_siege",
                    },
                    {
                        "gid": "pl_cvc",
                        "label": "CvC priority",
                        "fmt": "cvc_priority",
                        "inline_with": "pl_cvc_points",
                    },
                    {
                        "gid": "pl_cvc_points",
                        "label": "Minimum CvC points",
                        "fmt": "abbr_number",
                        "inline": True,
                    },
                ],
            },
            {
                "name": "rationale",
                "title": "🧭 Move rationale & constraints",
                "fields": [
                    {"gid": "pl_move_reason", "label": "Move reason", "truncate": 200},
                    {"gid": "pl_move_urgency", "label": "Move urgency"},
                    {"gid": "pl_move_window", "label": "Move window", "truncate": 200},
                    {"gid": "pl_notes", "label": "Anything else we should know", "truncate": 280},
                ],
            },
        ],
    },
}

SUMMARY_FRAME = SUMMARY_LAYOUTS["welcome"]["frame"]
SUMMARY_SECTIONS = SUMMARY_LAYOUTS["welcome"]["sections"]

__all__ = ["SUMMARY_LAYOUTS", "SUMMARY_FRAME", "SUMMARY_SECTIONS"]
