"""Configuration for the recruitment welcome summary embed."""

from __future__ import annotations

SUMMARY_SECTIONS = [
    {
        "name": "identity",
        "fields": [
            {"gid": "w_ign", "label": "Player"},
            {
                "gid": "w_power",
                "label": "Power",
                "inline_with": "w_level_detail",
                "fmt": "abbr_number",
            },
            {"gid": "w_level_detail", "label": "Bracket", "inline": True},
            {"gid": "w_playstyle", "label": "Playstyle"},
            {"gid": "w_clan", "label": "Looking for"},
        ],
    },
    {
        "name": "bossing",
        "fields": [
            {"gid": "w_CB", "label": "Clan Boss (one-key top chest)"},
            {"gid": "w_hydra_diff", "label": "Hydra"},
            {
                "gid": "w_hydra_clash",
                "label": "Avg Hydra Clash",
                "inline_with": "w_hydra_diff",
                "fmt": "abbr_number",
            },
            {"gid": "w_chimera_diff", "label": "Chimera"},
            {
                "gid": "w_chimera_clash",
                "label": "Avg Chimera Clash",
                "inline_with": "w_chimera_diff",
                "fmt": "abbr_number",
            },
        ],
    },
    {
        "name": "war",
        "fields": [
            {"gid": "w_siege", "label": "Siege participation"},
            {
                "gid": "w_siege_detail",
                "label": "Siege setup",
                "hide_if_values": ["", "no", "none"],
            },
            {"gid": "w_cvc", "label": "CvC priority", "fmt": "cvc_priority"},
            {
                "gid": "w_cvc_points",
                "label": "Minimum CvC points",
                "fmt": "abbr_number",
            },
        ],
    },
    {
        "name": "notes",
        "fields": [
            {
                "gid": "w_level",
                "label": "Progression (self-feel)",
                "optional": True,
                "truncate": 200,
            },
            {"gid": "w_origin", "label": "Heard about C1C from"},
        ],
    },
]

SUMMARY_FRAME = {
    "title": "C1C • Recruitment Summary",
    "description": "Keep this thread open until a recruiter confirms placement.",
    "icon": "crest_or_blue_flame",
    "color": "c1c_blue",
    "footer": "C1C Recruitment • Summary generated by The Woadkeeper",
}

__all__ = ["SUMMARY_FRAME", "SUMMARY_SECTIONS"]
