name: feature-setup-shards-mercy
on: { workflow_dispatch: {} }

permissions:
  contents: read
  issues: write

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run full setup
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PROJECTS_TOKEN }}  # PAT with project:write scope
          script: |
            const fs = require('fs');
            const code = fs.readFileSync('.github/scripts/feature-setup-shards-mercy.js','utf8');
            const AsyncFunction = Object.getPrototypeOf(async function(){}).constructor;
            await new AsyncFunction('github','context','core', code)(github, context, core);
