name: audit-coreops

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '**'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Run CoreOps packaging audit
        run: python scripts/audit_coreops_packaging.py
      - name: Run COMMAND_PREFIX audit
        run: python scripts/audit_command_prefix_usage.py
      - name: Upload audit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coreops-packaging-audit
          path: AUDIT/CoreOps-Packaging-Audit.md
      - name: Upload COMMAND_PREFIX audit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: command-prefix-audit
          path: AUDIT/CommandPrefix-Audit.md
