name: 04-config-guardrails

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  guardrails:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run config/docs parity & secret-pattern guard
        run: |
          python scripts/ci/check_env_parity.py
