name: 04-config-guardrails

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  guardrails:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run config/docs parity & secret-pattern guard
        id: parity
        continue-on-error: true
        run: |
          python scripts/ci/check_env_parity.py --summary guardrails-summary.md
      - name: Post guardrails summary comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const marker = '<!-- guardrails-summary -->';
            let body = marker + '\n';
            try {
              body += fs.readFileSync('guardrails-summary.md', 'utf8').trim() + '\n';
            } catch (error) {
              body += 'Guardrails summary unavailable.\n';
            }
            body += marker;

            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              per_page: 100,
            });

            const existing = comments.find((comment) => comment.body.includes(marker));
            if (existing) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existing.id,
                body,
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body,
              });
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Fail on guardrails issues
        if: steps.parity.outcome == 'failure'
        run: exit 1
