name: 13-auto-docs-lint

on:
  pull_request:
    paths:
      - 'docs/**'
      - '**/.env.example'
      - '.github/workflows/docs-lint.yml'
      - '!AUDIT/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run docs checker (capture output)
        id: docs
        continue-on-error: true
        run: |
          set -o pipefail
          python scripts/ci/check_docs.py --summary docs-summary.md 2>&1 | tee docs_lint.out
        shell: bash

      - name: Annotate failures directly in PR
        if: always()
        run: |
          python scripts/ci/emit_annotations.py --kind docs --input docs_lint.out
        shell: bash

      - name: Post docs lint summary comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const marker = '<!-- docs-lint-summary -->';
            let body = marker + '\n';
            try {
              body += fs.readFileSync('docs-summary.md', 'utf8').trim() + '\n';
            } catch (error) {
              body += 'Docs lint summary unavailable.\n';
            }
            body += marker;

            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              per_page: 100,
            });

            const existing = comments.find((comment) => comment.body.includes(marker));
            if (existing) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existing.id,
                body,
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body,
              });
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fail on docs lint issues
        if: steps.docs.outcome == 'failure'
        run: exit 1
