name: 12-auto-Guardrails check
on:
  pull_request:
    paths:
      - "**/*.py"
      - "docs/**"
      - ".env.example"

jobs:
  guardrails:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run guardrails checker
        run: python scripts/ci/guardrails_check.py
