name: Sync Labels
on:
  workflow_dispatch: {}
  push:
    paths:
      - .github/labels/labels.yml

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      # Uses a well-maintained action that reads YAML/JSON and syncs labels safely.
      - name: Sync labels from registry
        uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels/labels.json
          delete-other-labels: false
